import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const zh = {
  nav: { home: "首页", about: "关于我们", services: "服务体系", solutions: "行业方案", technology: "科技平台", contact: "联系我们", track: "货物追踪", quote: "立即询价", menu: "打开导航", language: "切换至英文" },
  common: { learn: "了解详情", consult: "获取专属方案", view: "查看全部", pending: "待替换", submit: "提交", sending: "正在提交...", required: "请完整填写必填信息。", email: "请输入有效的邮箱地址。", phone: "请输入有效的手机号码。", success: "提交成功，专属顾问将在 24 小时内联系您。", demo: "演示数据" },
  home: {
    eyebrow: "全球智慧物流 · 始于 2020", title: "高效连接世界\n全程精准可视", lead: "Vasilia 连接人、资产与数据，以公路、铁路、航空、海运和智能仓储，为全球贸易提供安全、贴心的一站式物流服务。",
    metrics: [{ value: "200+", label: "覆盖国家与地区" }, { value: "50,000+", label: "累计服务客户" }, { value: "99.8%", label: "货物安全率" }, { value: "24H", label: "全天候客服" }],
    servicesTitle: "一套网络，协同每一种运输方式", servicesLead: "从单票货物到复杂供应链，由同一团队、同一标准和同一可视化窗口全程统筹。",
    services: [{ title: "多式联运", text: "海陆空铁灵活组合，优化时效与成本。" }, { title: "智能仓储", text: "WMS 驱动库存、库位与履约实时协同。" }, { title: "国际物流", text: "覆盖进口、出口与跨境电商全链路。" }, { title: "科技赋能", text: "IoT、大数据与 AI 提供预测洞察。" }],
    industriesTitle: "深耕行业，量身定制", industries: ["制造业", "电商零售", "医药健康", "跨境贸易", "大宗货物"],
    industryCopy: ["JIT 配送与 VMI 仓库保障生产节奏。", "弹性仓容与逆向物流应对大促波峰。", "GSP 冷链专线与全程电子化追溯。", "海外仓、清关与末端配送一体化。", "超限专线与项目制运输保障安全交付。"],
    techTitle: "智能驱动每一步", techText: "IoT 实时采集位置、温度与状态，大数据持续优化路线，AI 主动识别异常，让每次运输更可控。",
    testimonial: "Vasilia 将跨境配送周期缩短了 31%，更重要的是，我们第一次真正看清了每一票货物。", testimonialBy: "待替换：合作客户 / 供应链负责人",
    quoteTitle: "告诉我们货物要去哪里", quoteLead: "填写三个关键信息，即刻开启一对一方案咨询。"
  },
  about: {
    eyebrow: "关于 Vasilia", title: "我们连接的不只是货物", lead: "创立于 2020 年，以技术与专业服务让全球贸易更高效、更精准、更安全、更贴心。",
    storyTitle: "从一条路线，到一张全球网络", story: "Vasilia 从服务中国制造企业的复杂运输需求出发，持续整合公路、铁路、航空、海运与仓储资源。我们相信，物流不是简单地把货物从 A 点送到 B 点，而是用数据、经验与责任感，让客户的供应链成为增长动力。",
    values: [{ title: "高效", text: "科学配置资源，缩短每个交付环节。" }, { title: "精准", text: "以数据提升预测、计划与库存准确性。" }, { title: "安全", text: "从合规、监控到异常处置全程保障。" }, { title: "贴心", text: "全天候响应，以主动沟通建立长期信任。" }],
    timeline: [{ year: "2020", text: "Vasilia 创立，搭建国内运输网络" }, { year: "2021", text: "上线智能仓储与 WMS 服务" }, { year: "2022", text: "国际海空运业务全面启航" }, { year: "2023", text: "IoT 追踪与数据控制塔投入使用" }, { year: "2024", text: "形成五大行业解决方案矩阵" }],
    team: [{ title: "物流规划师", text: "设计路线、成本与时效的最优组合。" }, { title: "运输调度员", text: "统筹运力并快速处理在途异常。" }, { title: "仓储管理员", text: "保障库存、拣选与出库准确高效。" }, { title: "客户服务专员", text: "提供 24 小时主动进度沟通。" }],
    partnersTitle: "并肩前行的合作伙伴", partners: ["待替换 · 航空伙伴", "待替换 · 船运伙伴", "待替换 · 铁路伙伴", "待替换 · ERP 伙伴", "待替换 · 电商平台", "待替换 · 保险伙伴"],
    honors: [{ title: "年度物流企业", text: "待替换：获奖年份与颁发机构" }, { title: "ISO 9001", text: "待替换：认证编号" }, { title: "AEO 高级认证", text: "待替换：认证信息" }]
  },
  services: {
    eyebrow: "一站式物流服务体系", title: "每种运输方式，协同运转", lead: "从运输到仓储、冷链与国际业务，一支团队负责到底。",
    transport: [{ title: "公路运输", text: "整车、零担、跨境卡车与同城急送", tags: ["FTL", "LTL", "最后一公里"] }, { title: "铁路运输", text: "中欧班列与海铁联运稳定连接欧亚", tags: ["中欧班列", "节点追踪"] }, { title: "航空货运", text: "国内国际空运、优先舱位与包机服务", tags: ["优先舱位", "门到门"] }, { title: "海运服务", text: "覆盖主要港口的整箱、拼箱和项目货", tags: ["FCL", "LCL", "特种柜"] }],
    wareTitle: "智能仓储，让库存与履约同步", wareText: "WMS 管理入库、库位、拣选、出库与盘点，满足常温、冷藏、保税和危化品仓储需求。", wareTypes: ["常温仓", "冷藏仓", "保税仓", "危化品仓"],
    coldTitle: "全程温控，守护敏感货物", cold: [{ title: "-25°C 至 +15°C", text: "多温区运输与仓储能力" }, { title: "实时温度监控", text: "异常阈值自动预警" }, { title: "GDP / GSP 合规", text: "电子记录全程可追溯" }],
    globalTitle: "跨境全链路服务", global: [{ title: "国际进口", text: "提货、报关、清关与国内配送。" }, { title: "国际出口", text: "订舱、单证、运输与目的港交付。" }, { title: "跨境电商", text: "海外仓、平台对接与末端履约。" }],
    customTitle: "找不到合适方案？", customText: "专属物流规划师将结合货物、路线和交付目标，为您提供一对一定制。",
    process: ["需求咨询", "方案报价", "签约下单", "运输执行", "签收售后"]
  },
  solutions: {
    eyebrow: "行业解决方案", title: "深耕行业，精准破题", lead: "理解行业节奏、合规要求与交付目标，才能设计真正有效的供应链。",
    tabs: ["制造业", "电商零售", "医药健康", "跨境贸易", "大宗货物"],
    details: [
      { title: "制造业供应链", text: "以准时、稳定的物料流保障生产连续性。", pains: ["供应链延误", "大件货物难运", "库存成本高"], solutions: ["JIT 配送", "超限专线", "VMI 仓库"] },
      { title: "电商零售履约", text: "用弹性资源承接流量高峰与多渠道订单。", pains: ["大促爆仓", "退换货低效", "末端时效差"], solutions: ["弹性仓容", "逆向物流", "次日达"] },
      { title: "医药健康冷链", text: "让温度、记录和交付全过程符合规范。", pains: ["冷链断链风险", "合规追溯要求"], solutions: ["GSP 冷链专线", "电子化记录"] },
      { title: "跨境贸易服务", text: "打通海外仓、清关、干线与末端配送。", pains: ["清关复杂", "节点不可视", "多渠道库存"], solutions: ["关务协同", "全程追踪", "海外仓一盘货"] },
      { title: "大宗与项目物流", text: "针对超长、超重和高价值货物制定专案。", pains: ["运输难度高", "安全风险", "协调链路长"], solutions: ["勘察与路勘", "专用运力", "项目控制塔"] }
    ],
    casesTitle: "客户成功案例", cases: [{ tag: "汽车制造", value: "99.5%", label: "JIT 准时率", text: "待替换：某汽车集团案例" }, { tag: "头部电商", value: "2.3 天", label: "平均配送周期", text: "待替换：电商履约案例" }, { tag: "医药健康", value: "零断链", label: "冷链交付记录", text: "待替换：三甲医院案例" }],
    cta: "您的行业不在列表？让我们一起定义方案。"
  },
  technology: {
    eyebrow: "科技与平台", title: "科技驱动，智慧物流", lead: "IoT、大数据、AI 与 WMS 共同构成 Vasilia 的数字物流底座。",
    capabilities: [{ title: "IoT 实时监控", text: "持续采集位置、温度、湿度和设备状态。" }, { title: "大数据分析", text: "预测需求、识别风险并持续优化路线。" }, { title: "AI 智能应用", text: "智能分拣、补货建议与秒级服务响应。" }, { title: "WMS 仓储系统", text: "库存、库位、订单与绩效统一管理。" }],
    trackingTitle: "货物追踪演示", trackingLead: "输入演示运单号 VAS20260618 查看实时状态。", trackingPlaceholder: "请输入运单号", trackingButton: "立即追踪", trackingLoading: "正在连接控制塔...", trackingEmpty: "未找到该运单，请核对后重试。", status: "当前状态", location: "当前位置", temperature: "货物温度", eta: "预计到达",
    wmsTitle: "从入库到报表，一套系统贯通", wmsText: "标准化流程与实时数据帮助仓储团队提升准确率、周转率和峰值履约能力。", modules: ["入库管理", "库位优化", "智能拣货", "出库复核", "循环盘点", "经营报表"],
    metrics: [{ value: "30%", label: "路线优化节省成本" }, { value: "98.6%", label: "库存准确率" }, { value: "<3s", label: "AI 平均响应" }, { value: "500万+", label: "日均数据处理" }],
    apiTitle: "开放连接企业系统", apiText: "标准 API 支持 ERP、电商平台和客户自有系统快速接入。", platforms: ["SAP", "Oracle ERP", "京东", "淘宝", "Shopify", "Custom API"]
  },
  contact: {
    eyebrow: "联系我们", title: "与我们携手合作", lead: "无论是一次运输，还是供应链长期升级，我们都将在 24 小时内响应。",
    channels: [{ title: "400 服务热线", text: "待替换：400 000 0000" }, { title: "在线客服", text: "演示：平均 30 秒响应" }, { title: "邮件咨询", text: "待替换：info@vasilia.com" }, { title: "微信公众号", text: "待替换：公众号二维码" }],
    formTitle: "在线询价", formLead: "请填写以下信息，带 * 为必填项。", fields: { company: "公司名称", name: "联系人", phone: "手机号", email: "邮箱", industry: "所属行业", origin: "出发地", destination: "目的地", cargo: "货物类型", message: "需求描述" },
    mapTitle: "全国服务网点", mapLead: "选择城市查看网点信息；位置为演示数据。", headquarters: "总部信息", address: "待替换：上海市 XX 路 XXX 号", hours: "工作时间：周一至周五 9:00–18:00",
    joinTitle: "合作加盟", join: [{ title: "代理合作", text: "共同开发行业与区域客户。" }, { title: "城市合伙人", text: "共享网络、产品与运营能力。" }, { title: "加盟商招募", text: "接入标准化物流服务体系。" }],
    complaintTitle: "投诉与建议", complaint: "待替换：complaint@vasilia.com · 400 热线转 2；承诺 48 小时内处理回复。"
  },
  footer: { desc: "以技术和专业服务连接全球贸易。", links: "快速导航", contact: "联系信息", email: "待替换：info@vasilia.com", phone: "待替换：400 000 0000", address: "待替换：中国 · 上海", legal: "© 2026 Vasilia Logistics · 备案信息待替换" }
};

const en = {
  ...zh,
  nav: { home: "Home", about: "About", services: "Services", solutions: "Solutions", technology: "Technology", contact: "Contact", track: "Track shipment", quote: "Get a quote", menu: "Open navigation", language: "Switch to Chinese" },
  common: { learn: "Learn more", consult: "Get a tailored plan", view: "View all", pending: "To be updated", submit: "Submit", sending: "Submitting...", required: "Please complete all required fields.", email: "Enter a valid email address.", phone: "Enter a valid phone number.", success: "Submitted. A specialist will contact you within 24 hours.", demo: "Demo data" },
  home: { ...zh.home, eyebrow: "GLOBAL INTELLIGENT LOGISTICS · SINCE 2020", title: "One network\nTotal visibility", lead: "Vasilia connects people, assets and data across road, rail, air, ocean and smart warehousing for efficient, precise, secure and thoughtful logistics worldwide.", metrics: [{ value: "200+", label: "Countries & regions" }, { value: "50,000+", label: "Customers served" }, { value: "99.8%", label: "Cargo safety rate" }, { value: "24/7", label: "Customer support" }], servicesTitle: "One network. Every mode working together.", servicesLead: "From a single shipment to a complex supply chain, one team and one visibility layer coordinate every move.", services: [{ title: "Multimodal", text: "Flexible ocean, air, road and rail combinations." }, { title: "Smart warehousing", text: "WMS-powered inventory and fulfillment." }, { title: "Global logistics", text: "End-to-end import, export and cross-border service." }, { title: "Technology", text: "IoT, data and AI deliver predictive insight." }], industriesTitle: "Solutions tailored to your industry", industries: ["Manufacturing", "E-commerce", "Healthcare", "Cross-border", "Project cargo"], industryCopy: ["JIT delivery and VMI warehousing protect production.", "Elastic capacity and returns for peak demand.", "GSP cold chain with electronic traceability.", "Overseas warehousing, customs and last mile.", "Dedicated routes for oversized project cargo."], techTitle: "Intelligence in every move", techText: "IoT captures location, temperature and condition in real time. Data optimizes routes while AI spots exceptions before they grow.", testimonial: "Vasilia shortened our cross-border delivery cycle by 31%. More importantly, we can finally see every shipment.", testimonialBy: "To be updated: Customer / Supply Chain Director", quoteTitle: "Tell us where your cargo needs to go", quoteLead: "Three details are enough to begin a tailored logistics plan." },
  about: { ...zh.about, eyebrow: "ABOUT VASILIA", title: "We connect more than cargo", lead: "Founded in 2020, we combine technology and expert service to make global trade efficient, precise, secure and thoughtful.", storyTitle: "From one route to a global network", story: "Vasilia began by solving complex transport needs for Chinese manufacturers, then integrated road, rail, air, ocean and warehousing resources. Logistics is more than moving cargo from A to B. It is the discipline of turning data, experience and accountability into supply-chain growth.", values: [{ title: "Efficient", text: "Allocate resources scientifically and shorten every stage." }, { title: "Precise", text: "Use data to improve forecasting, planning and accuracy." }, { title: "Secure", text: "Protect every move through compliance and monitoring." }, { title: "Thoughtful", text: "Build trust through 24/7 proactive communication." }], timeline: [{ year: "2020", text: "Vasilia founded and domestic network launched" }, { year: "2021", text: "Smart warehousing and WMS introduced" }, { year: "2022", text: "International ocean and air freight launched" }, { year: "2023", text: "IoT tracking and control tower activated" }, { year: "2024", text: "Five industry solution practices established" }], team: [{ title: "Logistics planners", text: "Design the best route, cost and transit mix." }, { title: "Dispatchers", text: "Coordinate capacity and resolve exceptions." }, { title: "Warehouse operators", text: "Keep inventory and fulfillment accurate." }, { title: "Service specialists", text: "Provide proactive updates around the clock." }], partnersTitle: "Partners moving with us", partners: ["Update · Airline partner", "Update · Ocean partner", "Update · Rail partner", "Update · ERP partner", "Update · Commerce platform", "Update · Insurance partner"], honors: [{ title: "Logistics Company Award", text: "To be updated: year and issuer" }, { title: "ISO 9001", text: "To be updated: certificate" }, { title: "AEO Certification", text: "To be updated: certificate" }] },
  services: { ...zh.services, eyebrow: "END-TO-END LOGISTICS", title: "Every mode, working as one", lead: "Transport, warehousing, cold chain and global freight under one accountable team.", transport: [{ title: "Road freight", text: "FTL, LTL, cross-border trucking and express city delivery", tags: ["FTL", "LTL", "Last mile"] }, { title: "Rail freight", text: "Stable China-Europe and sea-rail connections", tags: ["China-Europe", "Milestones"] }, { title: "Air freight", text: "Domestic and global priority capacity and charter", tags: ["Priority", "Door-to-door"] }, { title: "Ocean freight", text: "FCL, LCL and project cargo across major ports", tags: ["FCL", "LCL", "Special equipment"] }], wareTitle: "Smart warehousing, synchronized fulfillment", wareText: "WMS manages receiving, locations, picking, dispatch and counts across ambient, chilled, bonded and dangerous-goods facilities.", wareTypes: ["Ambient", "Chilled", "Bonded", "Dangerous goods"], coldTitle: "Temperature control without compromise", cold: [{ title: "-25°C to +15°C", text: "Multi-zone transport and storage" }, { title: "Live temperature", text: "Automated threshold alerts" }, { title: "GDP / GSP ready", text: "Traceable electronic records" }], globalTitle: "Cross-border, end to end", global: [{ title: "International import", text: "Pickup, declaration, customs and domestic delivery." }, { title: "International export", text: "Booking, documents, freight and destination delivery." }, { title: "Cross-border commerce", text: "Overseas warehouses, integrations and fulfillment." }], customTitle: "Need something different?", customText: "A dedicated planner will design around your cargo, route and delivery priorities.", process: ["Discover", "Quote", "Confirm", "Execute", "Review"] },
  solutions: { ...zh.solutions, eyebrow: "INDUSTRY SOLUTIONS", title: "Industry depth. Precise answers.", lead: "Supply chains work better when logistics reflects the pace, compliance and delivery goals of each industry.", tabs: ["Manufacturing", "E-commerce", "Healthcare", "Cross-border", "Project cargo"], details: [{ title: "Manufacturing supply chain", text: "Dependable material flow protects production continuity.", pains: ["Supply delays", "Oversized cargo", "High inventory cost"], solutions: ["JIT delivery", "Dedicated routes", "VMI warehouse"] }, { title: "E-commerce fulfillment", text: "Elastic resources absorb campaigns and multichannel demand.", pains: ["Peak overflow", "Slow returns", "Last-mile delays"], solutions: ["Elastic capacity", "Reverse logistics", "Next-day delivery"] }, { title: "Healthcare cold chain", text: "Temperature, records and delivery stay compliant.", pains: ["Temperature risk", "Traceability"], solutions: ["GSP cold chain", "Electronic records"] }, { title: "Cross-border trade", text: "Connect overseas storage, customs, line haul and last mile.", pains: ["Complex customs", "Low visibility", "Fragmented stock"], solutions: ["Customs support", "Live tracking", "Unified stock"] }, { title: "Project logistics", text: "Dedicated plans for oversized, heavy and valuable cargo.", pains: ["Complex transport", "Safety risk", "Long coordination"], solutions: ["Route survey", "Dedicated capacity", "Project control tower"] }], casesTitle: "Customer success", cases: [{ tag: "Automotive", value: "99.5%", label: "JIT on-time rate", text: "To be updated: automotive group" }, { tag: "E-commerce", value: "2.3 days", label: "Average delivery", text: "To be updated: commerce case" }, { tag: "Healthcare", value: "Zero break", label: "Cold-chain record", text: "To be updated: hospital case" }], cta: "Not seeing your industry? Let us define the answer together." },
  technology: { ...zh.technology, eyebrow: "TECHNOLOGY PLATFORM", title: "Technology-powered logistics", lead: "IoT, data, AI and WMS form the digital foundation of Vasilia logistics.", capabilities: [{ title: "IoT monitoring", text: "Capture location, temperature, humidity and equipment condition." }, { title: "Data analytics", text: "Forecast demand, identify risk and optimize routes." }, { title: "Applied AI", text: "Smarter sorting, replenishment and service response." }, { title: "WMS platform", text: "Unify inventory, locations, orders and performance." }], trackingTitle: "Shipment tracking demo", trackingLead: "Enter demo number VAS20260618 to view a live status.", trackingPlaceholder: "Enter shipment number", trackingButton: "Track now", trackingLoading: "Connecting to control tower...", trackingEmpty: "Shipment not found. Check the number and try again.", status: "Status", location: "Location", temperature: "Cargo temperature", eta: "Estimated arrival", wmsTitle: "One system from receiving to reporting", wmsText: "Standard workflows and live data improve accuracy, turnover and peak fulfillment.", modules: ["Receiving", "Slotting", "Smart picking", "Dispatch check", "Cycle count", "Analytics"], metrics: [{ value: "30%", label: "Route cost savings" }, { value: "98.6%", label: "Inventory accuracy" }, { value: "<3s", label: "Average AI response" }, { value: "5M+", label: "Daily data points" }], apiTitle: "Open connections to enterprise systems", apiText: "Standard APIs connect ERP, commerce platforms and customer systems.", platforms: ["SAP", "Oracle ERP", "JD.com", "Taobao", "Shopify", "Custom API"] },
  contact: { ...zh.contact, eyebrow: "CONTACT VASILIA", title: "Let us move forward together", lead: "From one shipment to long-term supply-chain transformation, our team responds within 24 hours.", channels: [{ title: "Service hotline", text: "Update: +86 400 000 0000" }, { title: "Live service", text: "Demo: 30-second response" }, { title: "Email", text: "Update: info@vasilia.com" }, { title: "WeChat", text: "Update: QR code" }], formTitle: "Online inquiry", formLead: "Complete the form below. Fields marked * are required.", fields: { company: "Company", name: "Contact name", phone: "Phone", email: "Email", industry: "Industry", origin: "Origin", destination: "Destination", cargo: "Cargo type", message: "Requirements" }, mapTitle: "China service network", mapLead: "Select a city for office details. Locations are demo data.", headquarters: "Headquarters", address: "Update: XXX Road, Shanghai", hours: "Hours: Monday–Friday, 9:00–18:00", joinTitle: "Partner with us", join: [{ title: "Agency", text: "Develop industries and markets together." }, { title: "City partner", text: "Share network, products and operating capability." }, { title: "Franchise", text: "Join a standardized logistics service system." }], complaintTitle: "Complaints and suggestions", complaint: "Update: complaint@vasilia.com · hotline option 2; response promised within 48 hours." },
  footer: { desc: "Connecting global trade through technology and expert service.", links: "Quick links", contact: "Contact", email: "Update: info@vasilia.com", phone: "Update: +86 400 000 0000", address: "Update: Shanghai, China", legal: "© 2026 Vasilia Logistics · Filing details to be updated" }
};

const saved = localStorage.getItem("vasilia-language");
const detected = navigator.language.toLowerCase().startsWith("zh") ? "zh" : "en";

i18n.use(initReactI18next).init({ resources: { zh: { translation: zh }, en: { translation: en } }, lng: saved === "zh" || saved === "en" ? saved : detected, fallbackLng: "en", interpolation: { escapeValue: false } });

export default i18n;
